name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      Solution_Name: ActionsTest.sln
      Test_Project_Path: SomeLibTests\SomeLibTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      run: git fetch --prune --unshallow --tags

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Execute unit tests
      run: dotnet test --no-build --configuration Release
      
    - name: Release
      shell: bash
      run: |
        tag=$(git describe --always)
        release_name="ActionsTest-$tag-win-x64"
        
        dotnet publish ActionsTest\ActionsTest.csproj --runtime win-x64 -c Release -o ${release_name} --self-contained false
        
        7z a -tzip "${release_name}.zip" "./${release_name}/*"
        
        rm -r "$release_name"
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "ActionsTest-v*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}